default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.12
    hooks:
      # Run uv sync to sync dependencies
      - id: uv-sync
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix-only, --show-fixes, --extension, py:python, --respect-gitignore, -v]
      # Run the formatter.
      - id: ruff-format
        args: [--target-version, py313, --extension, py:python, --respect-gitignore, --line-length, '120', -v]
  #- repo: local
   # hooks:
       # Run the Static Type Checker
       #- id: ty-check
       # name: ty check
        #entry: uvx ty check . --ignore unresolved-import unresolved-reference
        #language: python
    #TODO maybe add pyright
    #TODO maybe add tests

