#!/bin/bash -e

cd "$(dirname "$0")"

if [ ! -f ./.venv/initialized ]; then
    python3 -m pip install --upgrade pip
    pip3 install virtualenv
    python3 -m venv .venv
    ./.venv/bin/pip install -r requirements.txt
    touch ./.venv/initialized
fi

exec ./venv/bin/python ./main.py $@