[project]
name = "niceshare"
version = "0.1.0"
description = "This is a simple Python GUI that displays data from table sheets (.ods) on a Website in a nice way. It is used for inventory management in organizations that lend stuff for free or vs donations."
authors = [{ name = "whoami", email = "schmusi@systemli.org" }]
requires-python = ">=3.14"
readme = "README.md"
license = "MIT"
dependencies = [
    "pydantic-settings>=2.14.1",
    "pyjwt>=2.13.0",
    "i18n-modern[yaml]>=0.2.4",
    "python-slugify>=8",
    "fastexcel==0.20.2",
    "ezodf>=0.3.2",
    "webdav4>=0.11.0",
    "lxml>=6.0.2",
    "email-validator>=2.3.0",
    "pillow>=12",
    "beautifulsoup4>=4",
    "qrcode>=8",
    "qtpy>=2.4.3",
    "polars>=1.40.1",
    "duckdb>=1.5.3",
    "pyarrow>=24.0.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "nicegui>=3.12.1",
    "xlsxwriter>=3.2.9",
]

[tool.hatch.build.targets.wheel]
packages = ["src/niceshare"]

[project.scripts]
niceshare = "niceshare:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
    "pre-commit>=4.6.0",
]
