[project]
name = "inventurgui"
version = "0.1.0"
description = "This is a simple Python GUI that displays data from table sheets (.ods) on a Website in a nice way. It is used for inventory management in organizations that lend stuff for free or vs donations."
authors = [{ name = "whoami", email = "schmusi@systemli.org" }]
requires-python = ">=3.14"
readme = "README.md"
license = "MIT"
dependencies = [
    "aiowebdav2>=0.5.0",
    "pandas>=3.0.0",
    "numpy>=2.4",
    "pandas-ods-reader>=1.0.1,<2",
    "pandas-stubs~=3.0.0",
    "pydantic-settings>=2.12.0",
    "httpx>=0.28.1",
    "pyjwt>=2.11.0",
    "nicegui>=3.7.1",
    "i18n-modern[yaml]>=0.2.1",
    "python-slugify>=8.0.4",
]

[tool.hatch.build.targets.wheel]
packages = ["src/inventurgui"]

[project.scripts]
inventurgui = "inventurgui:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
