title: IU Inventur
favicon: favicon.jpeg
language: 'de'
date_format: '%d.%m.%y' # https://strftime.org/
theme:
  primary: '#e89769'
  secondary: '#37474f'
  accent: '#607d8b'
  dark_page: '#0d1626'
  dark_mode: True
cloud:
  dir: "Infra United (Intern)/Inventur"
  pull:
    inventory: "IU_Inventur.ods"
    start: 'start.md'
    help: 'help.md'
    terms: 'terms.md'
    about: 'about.md'
  push:
    requests: 'IU_Anfragen.ods'
data:
  sheets: 3
  category: Kategorie
  count: Zahl
  desc: Art
  object: Objekt
  pack: Packung
  path: "IU_Inventur.ods"
everything: 'Alles'
menu:
  warehouse:
    label: 'Lager'
    icon: 'warehouse'
  start:
    label: 'Start'
    icon: 'home'
cart:
  label: 'Beladen'
  icon: 'local_shipping'
  edit_tip: "Belade die Fahrzeuge - Passe die Mengen an indem du auf sie klickst."
  select_tip: "Bitte wähle zunächst Dinge aus dem Lager aus die du einladen kannst."
  invalid_edit: "So viele haben wir nicht!"
request:
  label: 'Anfragen'
  icon: 'sym_o_delivery_truck_speed'
  form:
    label: 'Daten'
    icon: 'article'
    month: 'Monat'
    start: 'Abholung'
    end: 'Rückgabe'
    input:
      name: 'Camp/Organisation'
      place: 'Ort'
      donation: 'Geplante Spende'
      email: 'E-Mail'
    please_fill: 'Bitte fülle dieses Feld aus.'
    email_invalid: 'Dies ist keine gültige E-Mail-Adresse.'
    message: 'Deine Mail - Fragen, Anmerkungen und wichtige Infos'
    checkbox:
      terms: 'Ich habe die Leihbedingungen gelesen.'
    submit: 'Anfragen'
  terms:
    display: true
    label: 'Leihbedingungen'
    icon: 'policy'
    path: 'terms.md'
links:
  display: false
  column: "Link"
mail:
  subject: '[Anfrage] '
  mail_to: 'aberallesisgut@riseup.net'
start:
  about:
    display: true
    label: 'Über Uns'
    icon: 'info'
    path: 'about.md'
  how_to:
    display: true
    label: 'How To'
    icon: 'menu_book'
    path: 'start.md'
  help:
    display: true
    label: 'Hilfe'
    icon: 'help_outline'
    path: 'help.md'
  terms:
    display: true
    label: 'Leihbedingungen'
    icon: 'policy'
    path: 'terms.md'

