title: IU Inventur
favicon: logo.jpeg
domain: 'inventur.infraunited.org'
language: 'de' # The language to use on Quasar UI Components
date_format: '%d.%m.%y' # The format for dates - see https://strftime.org/
theme:
  primary: '#e89769'
  secondary: '#37474f'
  accent: '#607d8b'
  dark_page: '#0d1626'
  dark_mode: True
cloud:
  dir: "Infra United (Intern)/Inventur"
  pull:
    logo: 'logo.jpeg'
    start: 'lager.md'
    help: 'help.md'
    terms: 'terms.md'
    about: 'about.md'
    inventory: "IU_Inventur.ods"
  push:
    requests: 'IU_Anfragen.ods'
mail:
  subject_request: '[Anfrage]'
  subject_update: '[Update]'
  subject_failure: '[Fehler]'
  mail_to: 'aberallesisgut@riseup.net'
  admin: 'aberallesisgut@riseup.net'
data:
  sheets: 3
  category: Kategorie
  count: Zahl
  desc: Art
  object: Objekt
  pack: Packung
  path: "IU_Inventur.ods"
start:
  label: 'Start'
  icon: 'home'
  about:
    display: true
    label: 'Über Uns'
    icon: 'info'
    path: 'about.md'
  how_to:
    display: true
    label: 'How To'
    icon: 'menu_book'
    path: 'lager.md'
  help:
    display: true
    label: 'Hilfe'
    icon: 'help_outline'
    path: 'help.md'
  terms:
    display: true
    label: 'Leihbedingungen'
    icon: 'policy'
    path: 'terms.md'
warehouse:
  label: 'Lager'
  icon: 'warehouse'
  path: 'lager.md'
  everything: 'Alles'
  selection: 'Meine Auswahl'
cart:
  label: 'Palettieren'
  icon: 'sym_o_pallet'
  tab_icon: 'local_shipping'
  edit_tip: "Belade die Fahrzeuge - Passe die Mengen an indem du auf sie klickst."
  select_tip: "Bitte wähle erst etwas aus."
  invalid_edit: "So viele haben wir nicht!"
request:
  label: 'Beladen' # The url path of the requests page
  icon: 'sym_o_forklift' # The menu icon for the requests page
  form:
    label: 'Formular' # The label for the form tab on the page
    icon: 'article' # The icon for the form tab on the page
    input: # Will create input fields at the start of the form for any number of items
      name: 'Camp/Organisation' # This key is required
      place: 'Ort'
      donation: 'Geplante Spende'
      email: 'E-Mail'
      message: 'Deine Mail - Fragen, Anmerkungen und wichtige Infos'
    please_fill: 'Bitte fülle dieses Feld aus.' # All above input fields have to be filled
    checkbox: # Will create checkboxes at the end of the form for any number of items
      terms: 'Ich habe die Leihbedingungen gelesen.'
    # Comment this out if you don't want users to be able to include a message to the mails
    # Just String Settings
    month: 'Monat'
    start: 'Abholung'
    end: 'Rückgabe'
    email_invalid: 'Dies ist keine gültige E-Mail-Adresse.'
    update_message: 'Eine kurze Info was du verändert hast - das macht es uns leichter.'
    # Submit Button Settings
    send: 'Anfragen'
    update: 'Speichern'
    send_icon: 'outgoing_mail'
    update_icon: 'save'
    sent: "Angefragt"
    updated: "Bearbeitet"
    update_link: "Bearbeitungslink"
    processing: "Wir verarbeiten deine Anfrage - bitte warte einen Moment..."
    success: "Deine Anfrage wurde erfolgreich an uns gesendet - wir melden uns zeitnah bei dir. Du kannst deine Anfrage jederzeit unter diesem Link bearbeiten:"
    failure: "Etwas ist schiefgelaufen :/ Uns wurde eine Mail mit dem Fehler gesendet, wir melden uns zeitnah bei dir."
  terms: # Show terms to the user in a tab next to the form
    display: true # Set this to false if you don't need this
    label: 'Leihbedingungen'
    icon: 'policy'
    path: 'terms.md'
finish:
  label: 'Abfahrt'
  copy_link: 'Link kopieren'
  download: 'Liste Herunterladen'
  filename: 'IU'
  download_data: 'Du kannst eine Liste deiner Ladung hier herunterladen:'
links:
  display: false
  column: "Link"

