title: "Title"        # Enter a title for your web application (shows in the browser tab)
favicon: "favicon.jpeg"     # The relative or absolute path to your favicon (shows in the browser tab as logo)   

data:                # All the data related settings
  path: "datasheet.ods"   # Enter the relative or absolute path to your data file (ends in *.ods)
  category: "category"     # Enter the name (value of first cell) of the column you want to use for Categories (that will be displayed as tabs)
  object: "object"          # Enter the name (value of first cell) of the column you want to use for individual Objects (will be pinned to the left)
  desc: "description"               # Enter the name (value of first cell) of the column you want to use for Object Descriptions (will be right of pinned)
  count: "count"             # Enter the name (value of first cell) of the column you want to use for Object Count (will be right of the description)
  pack: "package"           # Enter the name (value of first cell) of the column you want to use for Package Name or "Piece" (will be on the right)

links: 
  display: False            # Display a link column with little ℹ️ icons
  column: "link"            # Enter the name (value of first cell) of the column you want to use for Links (will be next to pinned)

colors:              # The main colors used in the web application
  primary: '#254060'        # primary color - enter hexcode: #XYZXYZ 
  secondary: '#FD916B'      # secondary color - enter hexcode: #XYZXYZ

help: 
  display: True             # Display a help tab
  label: ''                 # Set a label (name) for the help tab - leave empty to display only the ? icon
  path: 'help.md'          # Give the relative or absolute path to your help file written in markdown (ends in *.md) 

everything: 
  display: True             # Display a tab that shows all the data
  label: 'show all'            # Set a label (name) fot the all data tab
