title: IU Inventur
favicon: favicon.jpeg
theme:
  primary: '#FD916B'
  secondary: '#254060'
  dark: True
data:
  sheets: 3
  category: Kategorie
  count: Zahl
  desc: Art
  object: Objekt
  pack: Packung
  path: "Infra United (Intern)/Inventur/IU_Inventur.ods"
help:
  display: true
  label: 'Start'
  icon: 'home'
  path: help.md
everything: 'Alles'
truck:
  label: 'Beladen'
  icon: 'local_shipping'
  edit_tip: "Belade die Fahrzeuge - Passe die Mengen an indem du auf sie klickst."
  select_tip: "Bitte wähle zunächst Dinge aus dem Lager aus und bringe sie an die Laderampe."
form:
  label: 'Anfragen'
  icon: 'edit_note'
  name: 'Camp/Organisation'
  place: 'Ort'
  start: 'Abholung'
  end: 'Rückgabe'
  email: 'E-Mail-Adresse'
  donation: 'Eingeplante Spende'
  checkbox: 'Ich habe die Leihbedingungen gelesen.'
  submit: 'Anfragen'
warehouse:
  label: 'Lager'
  icon: 'warehouse'
links:
  display: false
  column: "Link"
mail:
  subject: '[Anfrage] '
  mail_to: 'aberallesisgut@riseup.net'

